export interface RegionDefinition {
  id: string
  label: string
  center: [number, number, number]
  radii: [number, number, number]
  share: number
  color: string
  noiseSeed: number
}

export interface NeuronField {
  positions: Float32Array
  colors: Float32Array
  phases: Float32Array
  scales: Float32Array
  regionIndex: Uint8Array
  count: number
}

export interface ConnectionField {
  positions: Float32Array
  colors: Float32Array
  edgeCount: number
}

export interface FlowEdge {
  start: [number, number, number]
  end: [number, number, number]
  color: [number, number, number]
}

/*
 * Procedural brain data.
 *
 * This is the data generated by:
 *
 * src/utils/brainGenerator.ts
 */
export interface BrainData {
  neurons: NeuronField
  connections: ConnectionField
  fineConnections: ConnectionField
  flowEdges: FlowEdge[]
}

/*
 * Live PyTorch neuron.
 */
export interface LiveNeuron {
  id: number
  layer: number
  index: number
  activation: number
  label: string
}

/*
 * Live PyTorch connection.
 */
export interface LiveConnection {
  id: string
  source: number
  target: number
  weight: number
  bias: number
  signal: number
}

/*
 * Neural-network layer metadata.
 */
export interface LiveLayer {
  index: number
  size: number
  neuronIds: number[]
}

/*
 * One complete inference frame received
 * from the FastAPI WebSocket.
 */
export interface InferenceFrame {
  type: string
  timestamp: number

  model: {
    name: string
    inputSize: number
    hiddenSizes: number[]
    outputSize: number
    layers: LiveLayer[]
  }

  input: number[]

  neurons: LiveNeuron[]

  connections: LiveConnection[]

  output: number[]
}

/*
 * Currently selected neuron in the UI.
 */
export interface SelectedNeuron {
  id: number
  layer: number
  index: number
  activation: number
  label: string
}

/*
 * Statistics displayed by the HUD.
 */
export interface NetworkStats {
  neuronCount: number
  connectionCount: number
  activeNeurons: number
  averageActivation: number
  maximumActivation: number
  positiveWeights: number
  negativeWeights: number
  inferenceTime: number
}